# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2822bdfc5adb6a34a045751c99a40e8406eda3748e1cfefe925908fa881e8f72dca0a98177240f0c4cdd6ffd3acaae09252d1ee96aaa0326ea9e39293a47d5a0

test:
  secret_key_base: 956726aecd7293735e96500853d87944a0fec20cce62075a083e032fd73b695e6bbd658c021519a12ab4acbcc03c9cc8a93e711d607a531e3d32ecc3483a555c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
